version: '3'
services:
  botservice:
    container_name: tgpbot-staging
    image: umon-build.ugsdev.com:5000/tgpbot:staging
    ports:
     - "3978:80"
    environment:
     - ASPNETCORE_ENVIRONMENT=Staging
    restart: always

